### ISSUE TITLE
Banner issues with manual installation

### ISSUE THREAD

**Issue by ColonelPanics** [openflighthpc/flight-runway#4]
## The Problem

The banner is not found or properly loaded when doing a manual installation.

When following the manual installation instructions (currently the branch [fix/docs](https://github.com/openflighthpc/flight-runway/tree/fix/docs) is tracking changes to the README/process and is a more accurate reflection of my setup steps) the flight command will setup and run, however the issue comes with loading/displaying the banner. Output below:

```bash
[ec2-user@runway-manual ~]$ /opt/flight/bin/flight
Traceback (most recent call last):
	2: from /opt/flight/opt/runway/bin/banner:28:in `<main>'
	1: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- openflight/banner (LoadError)
Usage: flight COMMAND [[OPTION]... [ARGS]]
Perform high performance computing management activities.

Commands:
  flight help             Display help and usage information.
  flight shell            Enter a shell-like sandbox for a Flight command.

For more help on a particular command run:
  flight COMMAND help

Please report bugs to <flight@openflighthpc.org>
OpenFlight home page: <https://openflighthpc.org/>
```

## Diagnosis

On the RPM based installation of flight-runway, the banner file is located in `/opt/flight/opt/runway/embedded/lib/ruby/site_ruby/2.6.0/`. The flight command is able to locate and load this file in due to this being in the Ruby search path:
```
[root@runway-rpm ~]# /opt/flight/bin/ruby -e 'puts $:'
/opt/flight/opt/runway/embedded/lib/ruby/site_ruby/2.6.0
/opt/flight/opt/runway/embedded/lib/ruby/site_ruby/2.6.0/x86_64-linux
/opt/flight/opt/runway/embedded/lib/ruby/site_ruby
/opt/flight/opt/runway/embedded/lib/ruby/vendor_ruby/2.6.0
/opt/flight/opt/runway/embedded/lib/ruby/vendor_ruby/2.6.0/x86_64-linux
/opt/flight/opt/runway/embedded/lib/ruby/vendor_ruby
/opt/flight/opt/runway/embedded/lib/ruby/2.6.0
/opt/flight/opt/runway/embedded/lib/ruby/2.6.0/x86_64-linux
/opt/flight/opt/runway/embedded/lib/ruby/gems/2.6.0/gems/did_you_mean-1.3.0/lib
/opt/flight/opt/runway/embedded/lib/ruby/site_ruby/2.6.0
/opt/flight/opt/runway/embedded/lib/ruby/site_ruby/2.6.0/x86_64-linux
/opt/flight/opt/runway/embedded/lib/ruby/site_ruby
/opt/flight/opt/runway/embedded/lib/ruby/vendor_ruby/2.6.0
/opt/flight/opt/runway/embedded/lib/ruby/vendor_ruby/2.6.0/x86_64-linux
/opt/flight/opt/runway/embedded/lib/ruby/vendor_ruby
/opt/flight/opt/runway/embedded/lib/ruby/2.6.0
/opt/flight/opt/runway/embedded/lib/ruby/2.6.0/x86_64-linux
```

When compared to a system with system/RVM ruby installed and manual flight runway, the search path is a lot more generic:
```
[root@runway-manual ~]# ruby -e 'puts $:'
/usr/share/gems/gems/did_you_mean-1.2.0/lib
/usr/local/share/ruby/site_ruby
/usr/local/lib64/ruby/site_ruby
/usr/share/ruby/vendor_ruby
/usr/lib64/ruby/vendor_ruby
/usr/share/rubygems
/usr/share/ruby
/usr/lib64/ruby
```

## The Solution

As far as I can tell there are a couple of potential fixes to this:
- Copy the `openflight.rb` and `openflight` directory from `pkg/ruby` to one of the system ruby locations
- Add `/opt/flight/opt/runway/ruby` to the global Ruby search path (investigating this solution didn't seem to show a way of adding a ruby search path system-wide, only on a per-user basis by modifying `$LOAD_PATH` in bashrc)

**Comment by ColonelPanics** [comment]
I don't think this is a huge concern, manual installation is very uncommon in practice and it looks like the version of Ruby has changed since this issue was seen (along with many other things, I'm sure). Closing for now, will reopen if issue is hit again.
